CREATE TABLE IF NOT EXISTS project
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    parent_id   INT,
    start_date  TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_type   VARCHAR(255),
    title       VARCHAR(255),
    description VARCHAR(255),
    status      INT,
    project_id  INT,
    start_date  TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT IF NOT EXISTS FK_PROJECT_ON_PARENT FOREIGN KEY (parent_id) REFERENCES project (id);

ALTER TABLE task
    ADD CONSTRAINT IF NOT EXISTS FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id) on delete cascade;