CREATE TABLE IF NOT EXISTS project
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    parent_id   INT,
    start_date  TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_type   VARCHAR(255),
    title       VARCHAR(255),
    description VARCHAR(255),
    status      VARCHAR(64),
    project_id  INT,
    start_date  TIMESTAMP,
    update_date TIMESTAMP,
    user_id     INT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    role     VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT IF NOT EXISTS FK_PROJECT_ON_PARENT FOREIGN KEY (parent_id) REFERENCES project (id);

ALTER TABLE task
    ADD CONSTRAINT IF NOT EXISTS FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id) on delete cascade;

ALTER TABLE task
    ADD CONSTRAINT IF NOT EXISTS FK_TASK_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO users
SELECT *
FROM (SELECT 1, 'admin', 'ADMIN', 'password'
      UNION
      SELECT 2, 'user', 'USER', 'password')
WHERE NOT EXISTS(SELECT * FROM users)